### ISSUE TITLE
Why do we need to set AZURE_TENANT_ID, AZURE_CLIENT_ID, AZURE_CLIENT_SECRET?

### ISSUE THREAD

**Issue by arjunpa1** [rebotics/django-azure-communication-email#10]
Why do we need to set AZURE_TENANT_ID, AZURE_CLIENT_ID, AZURE_CLIENT_SECRET when we can send the mail using only the connection_string?

**Comment by dvazar** [comment]
Nowhere does it say that this is required. You can quite use the connection string as described in the README.
