### ISSUE TITLE
InvalidSenderUserName

### ISSUE THREAD

**Issue by bendavis78** [rebotics/django-azure-communication-email#6]
I've set this email backend up using `settings.AZURE_COMMUNICATION_CONNECTION_STRING`, however when I try to send mail using `send_mail`, I get this error:

```python
HttpResponseError: (InvalidSenderUserName) Email sender's username is invalid. Please use a username from the list of valid usernames configured by your admin.
Code: InvalidSenderUserName
Message: Email sender's username is invalid. Please use a username from the list of valid usernames configured by your admin.
```

**Comment by dvazar** [comment]
If you are using a username other than the default DoNotReply username, you will need to add it to your domain first. See [changing EmailFrom](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/email/add-azure-managed-domains#changing-mailfrom-and-from-display-name-for-azure-managed-domain).
